# Generated by Django 4.2.6 on 2024-02-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default="Rogue", max_length=200),
        ),
    ]
